---
liftGroup:
  G1:
    L1:
      - 0
      - 1
      - 3
      - 5
      - 7
    L2:
      - 0
      - 1
      - 3
      - 5
      - 7
      - 9
  G2:
    L3:
      - 0
      - 2
      - 4
      - 6
      - 8
      - 10
    L4:
      - 0
      - 2
      - 4
      - 6
      - 8
...